import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn, spawnSync, execFile } from 'node:child_process';
import { EventEmitter } from 'node:events';
import { PassThrough } from 'node:stream';
import { mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { statSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { deflateSync } from 'node:zlib';
import { createImageNormalizer, IMAGE_LIMITS } from '../image-processing.mjs';

const execute = promisify(execFile);
const available = ['ffmpeg', 'ffprobe'].every(binary => spawnSync(binary, ['-version'], { timeout: 3000, stdio: 'ignore' }).status === 0);
const encoders = available ? spawnSync('ffmpeg', ['-hide_banner', '-encoders'], { timeout: 3000, encoding: 'utf8' }).stdout ?? '' : '';
const webpEncoder = encoders.includes('libwebp');
const real = { skip: available ? false : 'Existing ffmpeg/ffprobe unavailable; no installation attempted' };
const error = (status, code) => e => e.status === status && e.code === code;
async function temp(t) {
  const root = await mkdtemp(path.join(tmpdir(), 'extra-image-test-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  return root;
}

// These minimal marker containers exercise process models only, never claim a
// successful native decode. All real image pixels below are generated by FFmpeg.
function modelJPEG(width = 4, height = 2) {
  const sof = Buffer.from('ffc00011080002000403011100021100031100', 'hex');
  sof.writeUInt16BE(height, 5); sof.writeUInt16BE(width, 7);
  return Buffer.concat([Buffer.from('ffd8', 'hex'), sof, Buffer.from('ffda000c03010002000300003f0000ffd9', 'hex')]);
}
function segment(marker, payload) {
  const header = Buffer.from([0xff, marker, 0, 0]); header.writeUInt16BE(payload.length + 2, 2);
  return Buffer.concat([header, payload]);
}
function exif(orientation = 6, bigEndian = false) {
  const tiff = Buffer.alloc(38), u16 = (n, offset) => bigEndian ? tiff.writeUInt16BE(n, offset) : tiff.writeUInt16LE(n, offset),
    u32 = (n, offset) => bigEndian ? tiff.writeUInt32BE(n, offset) : tiff.writeUInt32LE(n, offset);
  tiff.write(bigEndian ? 'MM' : 'II'); u16(42, 2); u32(8, 4); u16(2, 8);
  u16(0x112, 10); u16(3, 12); u32(1, 14); u16(orientation, 18);
  // A GPS IFD pointer is intentionally not followed. It and its data are removed.
  u16(0x8825, 22); u16(4, 24); u32(1, 26); u32(38, 30);
  return Buffer.concat([tiff, Buffer.from('SYNTHETIC_GPS_PRIVATE')]);
}
function withExif(bytes, orientation, bigEndian = false) {
  return Buffer.concat([bytes.subarray(0, 2), segment(0xe1, Buffer.concat([Buffer.from('Exif\0\0'), exif(orientation, bigEndian)])), bytes.subarray(2)]);
}
function crc32(bytes) {
  let n = 0xffffffff;
  for (const byte of bytes) { n ^= byte; for (let i = 0; i < 8; i++) n = n & 1 ? 0xedb88320 ^ (n >>> 1) : n >>> 1; }
  return (n ^ 0xffffffff) >>> 0;
}
function pngChunk(name, payload) {
  const header = Buffer.alloc(8), tail = Buffer.alloc(4); header.writeUInt32BE(payload.length); header.write(name, 4);
  tail.writeUInt32BE(crc32(Buffer.concat([header.subarray(4), payload])));
  return Buffer.concat([header, payload, tail]);
}
function riffChunk(name, payload) {
  const header = Buffer.alloc(8); header.write(name); header.writeUInt32LE(payload.length, 4);
  return Buffer.concat([header, payload, ...(payload.length & 1 ? [Buffer.alloc(1)] : [])]);
}
function riff(parts) {
  const header = Buffer.from('524946460000000057454250', 'hex'); header.writeUInt32LE(4 + parts.reduce((n, part) => n + part.length, 0), 4);
  return Buffer.concat([header, ...parts]);
}
function fakeSpawn(onStart = () => {}) {
  const calls = [];
  const fn = (binary, args, options) => {
    const child = new EventEmitter(); child.stdout = new PassThrough(); child.stderr = new PassThrough();
    child.kill = signal => { child.killedWith = signal; queueMicrotask(() => child.emit('close', null)); return true; };
    const call = { binary, args, options, child }; calls.push(call); queueMicrotask(() => onStart(call, calls.length)); return child;
  };
  return { fn, calls };
}
const modelProbe = { streams: [{ codec_type: 'video', codec_name: 'mjpeg', width: 4, height: 2 }] };
function modelStage(call, index) {
  if (index === 1) call.child.stdout.write(JSON.stringify(modelProbe));
  if (index === 2) writeFileSync(call.args.at(-1), Buffer.alloc(24));
  if (index === 3) writeFileSync(call.args.at(-1), modelJPEG());
  if (index === 4) call.child.stdout.write(JSON.stringify({ streams: [{ ...modelProbe.streams[0], nb_read_frames: '1' }] }));
  call.child.emit('close', 0);
}
async function synthetic(t, format = 'jpeg', { width = 80, height = 40, frames = 1, lossless = false, transparent = false } = {}) {
  const directory = await temp(t), filename = path.join(directory, `synthetic.${format}`);
  const source = transparent ? `color=c=red@0:s=${width}x${height}:r=1,format=rgba` : `color=c=black:s=${width}x${height}:r=1,drawbox=x=0:y=0:w=iw/2:h=ih/2:color=red:t=fill,drawbox=x=iw/2:y=0:w=iw/2:h=ih/2:color=green:t=fill,drawbox=x=0:y=ih/2:w=iw/2:h=ih/2:color=blue:t=fill,drawbox=x=iw/2:y=ih/2:w=iw/2:h=ih/2:color=white:t=fill`;
  const codec = { jpeg: 'mjpeg', png: 'png', apng: 'apng', webp: 'libwebp' }[format];
  await execute('ffmpeg', ['-hide_banner', '-v', 'error', '-nostdin', '-f', 'lavfi', '-i', source, '-frames:v', String(frames),
    '-threads', '1', '-filter_threads', '1', '-c:v', codec, ...(format === 'jpeg' ? ['-q:v', '2', '-f', 'mjpeg'] : format === 'apng' ? ['-f', 'apng'] : format === 'webp' ? ['-lossless', lossless ? '1' : '0', '-f', 'webp'] : ['-f', 'image2']), filename], { timeout: 10000, maxBuffer: 32768 });
  return readFile(filename);
}
async function corners(t, image) {
  const root = await temp(t), filename = path.join(root, 'output.jpg'); await writeFile(filename, image.bytes, { mode: 0o600 });
  const { stdout } = await execute('ffmpeg', ['-hide_banner', '-v', 'error', '-nostdin', '-i', filename, '-threads', '1', '-filter_threads', '1', '-pix_fmt', 'rgb24', '-f', 'rawvideo', 'pipe:1'], { encoding: 'buffer', timeout: 5000, maxBuffer: 1024 * 1024 });
  return [[.25, .25], [.75, .25], [.25, .75], [.75, .75]].map(([x, y]) => [...stdout.subarray((Math.floor(y * image.height) * image.width + Math.floor(x * image.width)) * 3, (Math.floor(y * image.height) * image.width + Math.floor(x * image.width)) * 3 + 3)]);
}

test('rejects unsupported, mismatched, malformed, oversized and overdimensioned inputs before spawning', async t => {
  const root = await temp(t), process = fakeSpawn(), normalize = createImageNormalizer({ tempRoot: root, testSpawn: process.fn });
  await assert.rejects(normalize('bytes', { contentType: 'image/jpeg' }), error(400, 'invalid_image'));
  await assert.rejects(normalize(Buffer.alloc(0), { contentType: 'image/jpeg' }), error(400, 'invalid_image'));
  await assert.rejects(normalize(Buffer.alloc(IMAGE_LIMITS.inputBytes + 1), { contentType: 'image/jpeg' }), error(413, 'image_too_large'));
  for (const contentType of ['image/svg+xml', 'image/gif', 'image/heic', 'image/jpeg;filename=x', 'image/png\n', 'video/webm']) await assert.rejects(normalize(modelJPEG(), { contentType }), error(415, 'unsupported_image_type'));
  for (const bytes of [Buffer.from('<svg/>'), modelJPEG().subarray(0, -2), Buffer.concat([modelJPEG(), modelJPEG()]), withExif(modelJPEG(), 9)]) await assert.rejects(normalize(bytes, { contentType: 'image/jpeg' }), error(422, 'invalid_image'));
  await assert.rejects(normalize(modelJPEG(), { contentType: 'image/png' }), error(422, 'invalid_image'));
  await assert.rejects(normalize(modelJPEG(4000, 3001), { contentType: 'image/jpeg' }), error(422, 'image_dimensions_exceeded'));
  assert.equal(process.calls.length, 0); assert.deepEqual(await readdir(root), []);
});

test('operator options and process injection are bounded', () => {
  for (const timeoutMs of [0, -1, 1.5, 60001, Infinity, '15000']) assert.throws(() => createImageNormalizer({ timeoutMs }), TypeError);
  for (const ffmpegPath of ['', '../ffmpeg', 'ffmpeg -i', 'ffmpeg\n']) assert.throws(() => createImageNormalizer({ ffmpegPath }), TypeError);
  for (const tempRoot of ['relative', '/tmp/invalid\n']) assert.throws(() => createImageNormalizer({ tempRoot }), TypeError);
});

test('admission is shared across factories, has no queue, and releases after failure', async t => {
  const root = await temp(t), process = fakeSpawn(), a = createImageNormalizer({ tempRoot: root, testSpawn: process.fn }), b = createImageNormalizer({ tempRoot: root, testSpawn: process.fn });
  const first = a(modelJPEG(), { contentType: 'image/jpeg' });
  await assert.rejects(b(modelJPEG(), { contentType: 'image/jpeg' }), error(429, 'image_busy'));
  while (!process.calls.length) await new Promise(resolve => setImmediate(resolve));
  process.calls[0].child.emit('close', 1); await assert.rejects(first, error(422, 'invalid_image'));
  const next = fakeSpawn(modelStage); assert.equal((await createImageNormalizer({ tempRoot: root, testSpawn: next.fn })(modelJPEG(), { contentType: 'image/jpeg' })).contentType, 'image/jpeg');
  assert.deepEqual(await readdir(root), []);
});

test('every subprocess uses private files, file-only formats, bounded threads and no inherited environment', async t => {
  const root = await temp(t), process = fakeSpawn((call, index) => {
    assert.equal(call.options.shell, false); assert.deepEqual(call.options.stdio, ['ignore', 'pipe', 'pipe']);
    assert.deepEqual(Object.keys(call.options.env).sort(), ['LANG', 'LC_ALL', 'PATH']);
    assert.equal(statSync(call.options.cwd).mode & 0o777, 0o700);
    for (const name of ['input', 'decoded.rgb', 'image.jpg']) assert.equal(statSync(path.join(call.options.cwd, name)).mode & 0o777, 0o600);
    for (const [flag, value] of [['-protocol_whitelist', 'file'], ['-threads', '1'], ['-max_alloc', String(IMAGE_LIMITS.allocationBytes)]]) assert.equal(call.args[call.args.indexOf(flag) + 1], value);
    assert.ok(call.args.includes('-codec_whitelist')); assert.ok(call.args.includes('-format_whitelist'));
    if (index === 2) { assert.equal(call.args[call.args.indexOf('-frames:v') + 1], '2'); assert.equal(call.args[call.args.indexOf('-fps_mode') + 1], 'passthrough'); assert.ok(call.args.includes('-noautorotate')); }
    modelStage(call, index);
  });
  const result = await createImageNormalizer({ tempRoot: root, testSpawn: process.fn })(modelJPEG(), { contentType: 'image/jpeg' });
  assert.deepEqual({ ...result, bytes: undefined }, { bytes: undefined, contentType: 'image/jpeg', width: 4, height: 2 });
  assert.equal(process.calls.length, 4); assert.deepEqual(await readdir(root), []);
});

test('decoded frame count rejects multiple images even when the probe claims one still image', async t => {
  for (const bytes of [23, 48]) {
    const root = await temp(t), process = fakeSpawn((call, index) => {
      if (index === 2) { writeFileSync(call.args.at(-1), Buffer.alloc(bytes)); call.child.emit('close', 0); }
      else modelStage(call, index);
    });
    await assert.rejects(createImageNormalizer({ tempRoot: root, testSpawn: process.fn })(modelJPEG(), { contentType: 'image/jpeg' }), error(422, bytes === 48 ? 'animated_image_not_supported' : 'invalid_image'));
    assert.equal(process.calls.length, 2); assert.deepEqual(await readdir(root), []);
  }
});

test('a timeout and diagnostic overflow kill the child before private cleanup', async t => {
  for (const kind of ['timeout', 'stdout', 'stderr']) {
    const root = await temp(t), process = fakeSpawn(({ child }) => { if (kind !== 'timeout') child[kind].write(Buffer.alloc(IMAGE_LIMITS[`${kind}Bytes`] + 1)); });
    await assert.rejects(createImageNormalizer({ tempRoot: root, timeoutMs: 100, testSpawn: process.fn })(modelJPEG(), { contentType: 'image/jpeg' }), error(kind === 'timeout' ? 504 : 422, kind === 'timeout' ? 'image_processing_timeout' : 'image_processing_limit'));
    assert.equal(process.calls[0].child.killedWith, 'SIGKILL'); assert.deepEqual(await readdir(root), []);
  }
});

test('all subprocesses share one total deadline rather than resetting the timeout per stage', async t => {
  const root = await temp(t), process = fakeSpawn((call, index) => { if (index === 1) setTimeout(() => modelStage(call, index), 60); });
  await assert.rejects(createImageNormalizer({ tempRoot: root, timeoutMs: 110, testSpawn: process.fn })(modelJPEG(), { contentType: 'image/jpeg' }), error(504, 'image_processing_timeout'));
  assert.equal(process.calls.length, 2); assert.equal(process.calls[1].child.killedWith, 'SIGKILL'); assert.deepEqual(await readdir(root), []);
});

test('malformed probes, codec/dimension disagreements and missing tools fail without raw diagnostics', async t => {
  for (const value of ['not JSON', '{}', JSON.stringify({ streams: [] }), JSON.stringify({ streams: [{ ...modelProbe.streams[0], width: 5 }] }), JSON.stringify({ streams: [{ ...modelProbe.streams[0], codec_name: 'png' }] })]) {
    const root = await temp(t), process = fakeSpawn(({ child }) => { child.stdout.write(value); child.emit('close', 0); });
    await assert.rejects(createImageNormalizer({ tempRoot: root, testSpawn: process.fn })(modelJPEG(), { contentType: 'image/jpeg' }), error(422, 'invalid_image'));
    assert.deepEqual(await readdir(root), []);
  }
  const root = await temp(t), process = fakeSpawn(({ child }) => { child.emit('error', new Error('SYNTHETIC_SECRET_PATH')); child.emit('close', -2); });
  await assert.rejects(createImageNormalizer({ tempRoot: root, testSpawn: process.fn })(modelJPEG(), { contentType: 'image/jpeg' }), e => { assert.equal(e.message, 'image_processing_unavailable'); return error(503, 'image_processing_unavailable')(e); });
  assert.deepEqual(await readdir(root), []);
});

test('oversized output, metadata, truncation and a second decoded output frame are refused after encoding', async t => {
  for (const kind of ['size', 'metadata', 'truncated', 'frames', 'tags']) {
    const root = await temp(t), process = fakeSpawn((call, index) => {
      if (index === 3 && kind === 'size') { writeFileSync(call.args.at(-1), Buffer.alloc(IMAGE_LIMITS.outputBytes + 1)); call.child.emit('close', 0); }
      else if (index === 3 && kind === 'metadata') { const image = modelJPEG(); writeFileSync(call.args.at(-1), Buffer.concat([image.subarray(0, 2), segment(0xfe, Buffer.from('SYNTHETIC_PRIVATE')), image.subarray(2)])); call.child.emit('close', 0); }
      else if (index === 3 && kind === 'truncated') { writeFileSync(call.args.at(-1), modelJPEG().subarray(0, -2)); call.child.emit('close', 0); }
      else if (index === 4) { call.child.stdout.write(JSON.stringify({ streams: [{ ...modelProbe.streams[0], nb_read_frames: kind === 'frames' ? '2' : '1', ...(kind === 'tags' ? { tags: { comment: 'SYNTHETIC_PRIVATE' } } : {}) }] })); call.child.emit('close', 0); }
      else modelStage(call, index);
    });
    await assert.rejects(createImageNormalizer({ tempRoot: root, testSpawn: process.fn })(modelJPEG(), { contentType: 'image/jpeg' }), error(kind === 'size' ? 422 : 500, kind === 'size' ? 'image_processing_limit' : 'image_processing_failed'));
    assert.deepEqual(await readdir(root), []);
  }
});

test('source bytes are copied before awaits and metadata is absent from the decoder input', async t => {
  const root = await temp(t), bytes = withExif(modelJPEG(), 1), process = fakeSpawn((call, index) => {
    const input = readFileSync(path.join(call.options.cwd, 'input')); assert.deepEqual(input, modelJPEG()); assert.equal(input.includes(Buffer.from('SYNTHETIC')), false);
    modelStage(call, index);
  });
  const pending = createImageNormalizer({ tempRoot: root, testSpawn: process.fn })(bytes, { contentType: 'image/jpeg' }); bytes.fill(0);
  assert.equal((await pending).width, 4); assert.deepEqual(await readdir(root), []);
});

test('real JPEG and PNG pixels become one metadata-free JPEG with no upscaling', real, async t => {
  for (const format of ['jpeg', 'png']) {
    const bytes = await synthetic(t, format), root = await temp(t), result = await createImageNormalizer({ tempRoot: root })(bytes, { contentType: `image/${format}` });
    assert.equal(result.contentType, 'image/jpeg'); assert.equal(result.width, 80); assert.equal(result.height, 40);
    assert.ok(result.bytes.length <= IMAGE_LIMITS.outputBytes); assert.deepEqual(await readdir(root), []);
    const colours = await corners(t, result); assert.ok(colours[0][0] > 180); assert.ok(colours[2][2] > 180);
  }
});

test('real WebP generated by the existing FFmpeg encoder becomes JPEG', { skip: available && webpEncoder ? false : 'Existing FFmpeg has no WebP encoder for a synthetic fixture; Linux counter-test required' }, async t => {
  for (const lossless of [false, true]) {
    const bytes = await synthetic(t, 'webp', { lossless }), root = await temp(t), normalize = createImageNormalizer({ tempRoot: root });
    const result = await normalize(bytes, { contentType: 'image/webp' });
    assert.equal(result.width, 80); assert.equal(result.height, 40); assert.equal(result.contentType, 'image/jpeg');
    const extended = Buffer.alloc(10); extended[0] = 12; extended.writeUIntLE(79, 4, 3); extended.writeUIntLE(39, 7, 3);
    const parts = []; let hasExtended = false;
    for (let at = 12; at < bytes.length;) {
      const length = bytes.readUInt32LE(at + 4), end = at + 8 + length + (length & 1), part = Buffer.from(bytes.subarray(at, end));
      if (part.toString('ascii', 0, 4) === 'VP8X') { part[8] |= 12; hasExtended = true; }
      parts.push(part); at = end;
    }
    if (!hasExtended) parts.unshift(riffChunk('VP8X', extended));
    parts.push(riffChunk('EXIF', exif(6)), riffChunk('XMP ', Buffer.from('SYNTHETIC_XMP_PRIVATE')));
    const rotated = await normalize(riff(parts), { contentType: 'image/webp' });
    assert.equal(rotated.width, 40); assert.equal(rotated.height, 80); assert.equal(rotated.bytes.includes(Buffer.from('SYNTHETIC')), false);
    assert.deepEqual(await readdir(root), []);
  }
});

test('WebP container dimensions and stripped metadata agree with the decoder in the process model', async t => {
  const root = await temp(t), extended = Buffer.alloc(10), vp8 = Buffer.from('0000009d012a0400020000', 'hex');
  extended[0] = 12; extended.writeUIntLE(3, 4, 3); extended.writeUIntLE(1, 7, 3);
  const source = riff([riffChunk('VP8X', extended), riffChunk('VP8 ', vp8), riffChunk('EXIF', exif(1)), riffChunk('XMP ', Buffer.from('SYNTHETIC_PRIVATE'))]);
  const process = fakeSpawn((call, index) => {
    assert.equal(readFileSync(path.join(call.options.cwd, 'input')).includes(Buffer.from('SYNTHETIC')), false);
    if (index === 1) { call.child.stdout.write(JSON.stringify({ streams: [{ ...modelProbe.streams[0], codec_name: 'webp' }] })); call.child.emit('close', 0); }
    else modelStage(call, index);
  });
  const normalize = createImageNormalizer({ tempRoot: root, testSpawn: process.fn });
  assert.equal((await normalize(source, { contentType: 'image/webp' })).contentType, 'image/jpeg');
  extended.writeUIntLE(4, 4, 3);
  await assert.rejects(normalize(riff([riffChunk('VP8X', extended), riffChunk('VP8 ', vp8)]), { contentType: 'image/webp' }), error(422, 'invalid_image'));
  assert.equal(process.calls.length, 4); assert.deepEqual(await readdir(root), []);
});

test('real rotation and reflection apply all eight EXIF orientations to pixels, with metadata removed', real, async t => {
  const bytes = await synthetic(t), root = await temp(t), normalize = createImageNormalizer({ tempRoot: root });
  const baseline = await corners(t, await normalize(bytes, { contentType: 'image/jpeg' }));
  const orders = [[0, 1, 2, 3], [1, 0, 3, 2], [3, 2, 1, 0], [2, 3, 0, 1], [0, 2, 1, 3], [2, 0, 3, 1], [3, 1, 2, 0], [1, 3, 0, 2]];
  for (let orientation = 1; orientation <= 8; orientation++) {
    const result = await normalize(withExif(bytes, orientation, orientation % 2 === 0), { contentType: 'image/jpeg' });
    assert.equal(result.width, orientation >= 5 ? 40 : 80); assert.equal(result.height, orientation >= 5 ? 80 : 40);
    const colours = await corners(t, result);
    for (let i = 0; i < 4; i++) for (let channel = 0; channel < 3; channel++) assert.ok(Math.abs(colours[i][channel] - baseline[orders[orientation - 1][i]][channel]) < 20, `orientation ${orientation}, corner ${i}`);
    assert.equal(result.bytes.includes(Buffer.from('SYNTHETIC')), false); assert.equal(result.bytes.includes(Buffer.from('Exif')), false);
  }
  assert.deepEqual(await readdir(root), []);
});

test('real EXIF/GPS/XMP/comments and compressed PNG text never reach the decoder or output', real, async t => {
  const jpeg = await synthetic(t), png = await synthetic(t, 'png');
  const taggedJPEG = Buffer.concat([withExif(jpeg, 1).subarray(0, 2), segment(0xe1, Buffer.from('http://ns.adobe.com/xap/1.0/\0SYNTHETIC_XMP_PRIVATE')), segment(0xfe, Buffer.from('SYNTHETIC_COMMENT_PRIVATE')), withExif(jpeg, 1).subarray(2)]);
  const taggedPNG = Buffer.concat([png.subarray(0, 33), pngChunk('eXIf', exif(6)), pngChunk('tEXt', Buffer.from('comment\0SYNTHETIC_COMMENT_PRIVATE')), pngChunk('zTXt', Buffer.concat([Buffer.from('comment\0\0'), deflateSync(Buffer.from('SYNTHETIC_COMPRESSED_PRIVATE'))])), png.subarray(33)]);
  for (const [contentType, bytes] of [['image/jpeg', taggedJPEG], ['image/png', taggedPNG]]) {
    const root = await temp(t), seen = [];
    const result = await createImageNormalizer({ tempRoot: root, testSpawn: (binary, args, options) => {
      seen.push(binary); const input = readFileSync(path.join(options.cwd, 'input'));
      for (const tag of ['SYNTHETIC', 'Exif', 'eXIf', 'zTXt']) assert.equal(input.includes(Buffer.from(tag)), false);
      return spawn(binary, args, options);
    } })(bytes, { contentType });
    assert.equal(result.bytes.includes(Buffer.from('SYNTHETIC')), false); assert.equal(seen.length, 4); assert.deepEqual(await readdir(root), []);
    assert.equal(result.width, contentType === 'image/png' ? 40 : 80);
  }
});

test('real resizing stays within 1600 pixels and preserves aspect ratio', real, async t => {
  const root = await temp(t), result = await createImageNormalizer({ tempRoot: root })(await synthetic(t, 'png', { width: 1700, height: 850 }), { contentType: 'image/png' });
  assert.equal(result.width, 1600); assert.equal(result.height, 800); assert.ok(result.bytes.length <= IMAGE_LIMITS.outputBytes); assert.deepEqual(await readdir(root), []);
});

test('real transparent PNG pixels are composited onto black instead of exposing hidden colours', real, async t => {
  const root = await temp(t), result = await createImageNormalizer({ tempRoot: root })(await synthetic(t, 'png', { transparent: true }), { contentType: 'image/png' });
  for (const colour of await corners(t, result)) assert.ok(colour.every(channel => channel < 3));
  assert.deepEqual(await readdir(root), []);
});

test('real APNG and concatenated images are refused, including a lying animation frame-count header', real, async t => {
  const animation = await synthetic(t, 'apng', { frames: 2 }), still = await synthetic(t, 'png'), jpeg = await synthetic(t);
  const acTL = animation.indexOf(Buffer.from('acTL')); assert.ok(acTL >= 4);
  const lying = Buffer.from(animation), dataOffset = acTL + 4; lying.writeUInt32BE(1, dataOffset);
  lying.writeUInt32BE(crc32(lying.subarray(acTL, dataOffset + 8)), dataOffset + 8);
  const withoutCount = Buffer.concat([animation.subarray(0, acTL - 4), animation.subarray(acTL - 4 + 20)]);
  const root = await temp(t), process = fakeSpawn(), normalize = createImageNormalizer({ tempRoot: root, testSpawn: process.fn });
  for (const bytes of [animation, lying, withoutCount]) await assert.rejects(normalize(bytes, { contentType: 'image/png' }), error(422, 'animated_image_not_supported'));
  for (const [contentType, bytes] of [['image/png', Buffer.concat([still, still])], ['image/jpeg', Buffer.concat([jpeg, jpeg])]]) await assert.rejects(normalize(bytes, { contentType }), error(422, 'invalid_image'));
  assert.equal(process.calls.length, 0); assert.deepEqual(await readdir(root), []);
});

test('WebP animation chunks are rejected even when VP8X declares a still image', async t => {
  const root = await temp(t), process = fakeSpawn(), normalize = createImageNormalizer({ tempRoot: root, testSpawn: process.fn }), extended = Buffer.alloc(10);
  extended.writeUIntLE(3, 4, 3); extended.writeUIntLE(1, 7, 3);
  for (const name of ['ANIM', 'ANMF']) await assert.rejects(normalize(riff([riffChunk('VP8X', extended), riffChunk(name, Buffer.alloc(16))]), { contentType: 'image/webp' }), error(422, 'animated_image_not_supported'));
  extended[0] = 2; await assert.rejects(normalize(riff([riffChunk('VP8X', extended)]), { contentType: 'image/webp' }), error(422, 'animated_image_not_supported'));
  assert.equal(process.calls.length, 0); assert.deepEqual(await readdir(root), []);
});

test('real corrupt image data is refused with temporary data removed', real, async t => {
  const bytes = await synthetic(t, 'png'), corrupt = Buffer.from(bytes), at = corrupt.indexOf(Buffer.from('IDAT'));
  const length = corrupt.readUInt32BE(at - 4); corrupt.fill(0, at + 4, at + 4 + length); corrupt.writeUInt32BE(crc32(corrupt.subarray(at, at + 4 + length)), at + 4 + length);
  const root = await temp(t);
  await assert.rejects(createImageNormalizer({ tempRoot: root })(corrupt, { contentType: 'image/png' }), e => e.status === 422 && e.code === 'invalid_image');
  assert.deepEqual(await readdir(root), []);
});
